@startjson
{"nodes":{"id":"224DB16A6CE6DD5C8835E837C91423CFD2B341369F9326066CE8D9F72FE64","ip":"172.17.30.229","port":1432},"routes":{"buckets":[]},"rpc":{"awaiting_response":"{}","socket":"UdpSocket { addr: 172.17.30.229:1432, fd: 3 }","subscription_receiver":"Sender { .. }"},"store":[]}
@endjson