@startjson
{"nodes":{"id":"FF4BE6523FA7B3533BDD166C58C45CF4FDBB4BD1ECEC0DC109186D988A42C","ip":"0.0.0.0","port":1433},"routes":{"kbuckets":[{"nodes":{"id":"5C5CCD416D7BC8D4595E7E8934D9F09DC7EF1BC7EFE8ACF56A5B85A26D9","ip":"0.0.0.0","port":1432,"thrust":{"successfully_interaction":2,"total_interaction":2}},"size":32}]},"rpc":{"awaiting_response":"{}","socket":"UdpSocket { addr: 0.0.0.0:1433, fd: 6 }"},"store":[]}
@endjson