@startjson
{"nodes":{"id":"9AF8DF7FE8E6D2D2251FEC140AA63F210E94477A8C0F88D33A73E624AED22D","ip":"192.168.1.198","port":1430},"routes":{"kbuckets":[]},"rpc":{"awaiting_response":"{}","socket":"UdpSocket { addr: 192.168.1.198:1430, fd: 8 }"},"store":[]}
@endjson