@startjson
{"nodes":{"id":"84FAC38EE33CE22B8617425570E8C2DF26EF2AA33B2BC5C979BA2561AC692BB","ip":"0.0.0.0","port":1431},"routes":{"kbuckets":[]},"rpc":{"awaiting_response":"{}","socket":"UdpSocket { addr: 0.0.0.0:1431, fd: 4 }"},"store":[]}
@endjson