@startjson
{"nodes":{"id":"8615CA1DBAB64ADE33FBA86E52436E4309D7C8C8A50185567E0E0AFCC63C7","ip":"192.168.153.8","port":9876},"routes":{"buckets":[]},"rpc":{"awaiting_response":"{}","socket":"UdpSocket { addr: 192.168.153.8:9876, fd: 3 }","subscription_receiver":"Sender { .. }"},"store":[]}
@endjson